### ISSUE TITLE
(Naomi Stage 5) Black screen between 1st and 2nd checkpoint prevents progress.

### ISSUE THREAD

**Issue by TalentedJuli** [Kayinnasaki/BepIssueTracker#89]
![glitch1](https://cloud.githubusercontent.com/assets/13173892/12211034/40f7e18a-b613-11e5-8e2f-beaa30852b26.jpg)
![glitch2](https://cloud.githubusercontent.com/assets/13173892/12211038/431758ce-b613-11e5-921b-a7a0d99f1f5c.jpg)

When I jump on the platform that transitions to the next area, I get the black screen.  I tried just dropping down, rather than jumping onto it, and didn't get the glitch.  I'm not sure if jumping onto it is what causes the glitch, but that's my best guess.  The 2nd checkpoint is right after this transition, so I can't go back and test it again real easily.

In the black screen, I can attack and do special moves (sound effects play), and access the menu in order to quit the level, but I can't do anything else, or at least it has no noticeable effect.

**Comment by Kayinnasaki** [comment]
Seems to be a result of of hitting the back wall (or getting close enough to it) which causes you to miss a trigger. The jumping aspect probably came up because you 'bounce' when the platform falls, thus giving you more horizontal momentum.

Regardless, the triggers have been enlarged significantly.
